global:
  # uncomment next line if you want to provide your own hazelcast instance
  # hazelcast: hazelcast:5701
  replicas: 1
  port: 9000

service:
  type: ClusterIP
  port: 9000

image:
  repository: ghcr.io/camunda-community-hub/zeeqs
  tag: 2.0.0

resources: 
  requests:
    cpu: 500m
    memory: 1Gi
  limits:
    cpu: 1000m
    memory: 2Gi

hazelcast:
  enabled: true
